apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: ai-strategy-dev
data:
  DATABASE_URL: "postgresql://dev_user:dev_password@postgres-service:5432/ai_strategy_dev"
  REDIS_URL: "redis://redis-service:6379/0"
  JWT_SECRET: "dev-jwt-secret-change-in-production"
  LOG_LEVEL: "DEBUG"
  ENVIRONMENT: "development"
  CORS_ORIGINS: "http://localhost:3000,http://localhost:8080"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-dev
  namespace: ai-strategy-dev
  labels:
    app: api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-dev
  template:
    metadata:
      labels:
        app: api-dev
    spec:
      containers:
      - name: api
        image: localhost/ai-strategy-api:dev
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: api-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: ai-strategy-dev
spec:
  selector:
    app: api-dev
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
  type: NodePort