baseURL: 'https://nationwide-ai-strategy.github.io'
languageCode: 'en-us'
title: 'Nationwide AI Strategy Command Center'
theme: 'docsy'

# Repository information for GitHub Pages
repos:
  - https://github.com/nationwide-ai-strategy/ai-strategy-command-center

params:
  # Site info
  copyright: 'Nationwide Insurance'
  privacy_policy: '/privacy'
  
  # GitHub repository info
  github_repo: 'https://github.com/nationwide-ai-strategy/ai-strategy-command-center'
  github_branch: 'main'
  
  # Version and release info
  version: '1.0.0'
  version_menu: true
  
  # UI configuration
  ui:
    sidebar_menu_compact: true
    breadcrumb_disable: false
    navbar_logo: true
    navbar_translucent_over_cover_disable: false
    sidebar_search_disable: false
    feedback:
      enable: true
      'yes': >-
        Glad to hear it! Please <a
        href="https://github.com/nationwide-ai-strategy/ai-strategy-command-center/issues/new">tell
        us how we can improve</a>.
      'no': >-
        Sorry to hear that. Please <a
        href="https://github.com/nationwide-ai-strategy/ai-strategy-command-center/issues/new">tell
        us how we can improve</a>.
    readingtime:
      enable: false
  
  # Links for header and footer
  links:
    user:
      - name: 'GitHub Repository'
        url: 'https://github.com/nationwide-ai-strategy/ai-strategy-command-center'
        icon: 'fab fa-github'
        desc: 'View source code and contribute'
      - name: 'Internal Support'
        url: 'mailto:ai-strategy@nationwide.com'
        icon: 'fa fa-envelope'
        desc: 'Get support from AI Strategy team'
    developer:
      - name: 'GitHub'
        url: 'https://github.com/nationwide-ai-strategy'
        icon: 'fab fa-github'
        desc: 'Development on GitHub'
      - name: 'Slack Channel'
        url: '#ai-strategy'
        icon: 'fab fa-slack'
        desc: 'Chat with us on Slack'

# Menu configuration
menu:
  main:
    - name: 'Executive'
      url: '/executive/'
      weight: 10
    - name: 'Developers'
      url: '/developers/'
      weight: 20
    - name: 'Tools'
      url: '/tools/'
      weight: 30
    - name: 'Operations'
      url: '/operations/'
      weight: 40
    - name: 'Community'
      url: '/community/'
      weight: 50

# Markup configuration
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: 'github'
    lineNos: true
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    lineAnchors: ''
    lineNoStart: 1
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 4

# Security configuration
security:
  enableInlineShortcodes: false
  exec:
    allow:
      - '^dart-sass-embedded$'
      - '^go$'
      - '^npx$'
      - '^postcss$'
    osEnv:
      - '(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$'
  funcs:
    getenv:
      - '^HUGO_'
  http:
    methods:
      - '(?i)GET|POST'
    urls:
      - '.*'

# Build configuration
build:
  writeStats: true