http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline
path.logs: /var/log/logstash

# Pipeline settings
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Monitoring
xpack.monitoring.enabled: false
xpack.monitoring.elasticsearch.hosts: ["elasticsearch:9200"]

# Dead letter queue
dead_letter_queue.enable: true
dead_letter_queue.max_bytes: 1024mb

# Security settings
log.level: info
slowlog.threshold.warn: 2s
slowlog.threshold.info: 1s
slowlog.threshold.debug: 500ms
slowlog.threshold.trace: 100ms

# Queue settings
queue.type: persisted
queue.max_bytes: 1gb
queue.checkpoint.writes: 1024

# HTTP API settings
api.http.host: 0.0.0.0
api.http.port: 9600
api.environment: production

# Automatic config reload
config.reload.automatic: true
config.reload.interval: 3s

# JVM settings
jvm.options: |
  -Xms1g
  -Xmx1g
  -XX:+UseG1GC
  -XX:G1HeapRegionSize=16m
  -XX:+UnlockExperimentalVMOptions
  -XX:+UseCGroupMemoryLimitForHeap